apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-go-service-a
  namespace: simple-go-service-a
spec:
  ingressClassName: nginx
  rules:
    - host: simple-go-service-a.192.168.64.27.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-go-service-a
                port:
                  number: 80
