apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-go-service-a
  namespace: applications
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /health
spec:
  ingressClassName: nginx
  rules:
    - host: simple-go-service-a.192.168.50.10.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-go-service-a
                port:
                  number: 80
